"""Example configuration for the ESP32 MicroPython application."""

DEVICE_ENV = "local"

WIFI_SSID = "YOUR_WIFI_SSID"
WIFI_PASSWORD = "YOUR_WIFI_PASSWORD"
WIFI_TIMEOUT_SECONDS = 15

DEVICE_PROFILES = {
    "local": {
        "BACKEND_SCHEME": "http",
        "BACKEND_HOST": "192.168.1.50",
        "BACKEND_PORT": 8000,
        "MQTT_BROKER": "192.168.1.50",
        "MQTT_PORT": 1884,
        "MQTT_USE_TLS": False,
        "MQTT_KEEPALIVE": 60,
        "MQTT_USER": "local-mqtt-user",
        "MQTT_PASSWORD": "local-mqtt-password",
    },
    "server": {
        "BACKEND_SCHEME": "https",
        "BACKEND_HOST": "routine.84-247-128-231.sslip.io",
        "BACKEND_PORT": 443,
        "MQTT_BROKER": "routine.84-247-128-231.sslip.io",
        "MQTT_PORT": 8883,
        "MQTT_USE_TLS": True,
        "MQTT_KEEPALIVE": 0,
        "MQTT_USER": "server-mqtt-user",
        "MQTT_PASSWORD": "server-mqtt-password",
    },
}

_ACTIVE_PROFILE = DEVICE_PROFILES[DEVICE_ENV]

BACKEND_SCHEME = _ACTIVE_PROFILE["BACKEND_SCHEME"]
BACKEND_HOST = _ACTIVE_PROFILE["BACKEND_HOST"]
BACKEND_PORT = _ACTIVE_PROFILE["BACKEND_PORT"]
REMINDERS_ENDPOINT = "/api/voice/reminders"
AUDIO_ENDPOINT_PREFIX = "/assistant/audio/"
STT_ENDPOINT = "/assistant/stt/"
TEMP_AUDIO_DOWNLOAD_PATH = "/assistant_audio.wav"
HTTP_CONNECT_TIMEOUT_SECONDS = 15
HTTP_SEND_TIMEOUT_SECONDS = 30
HTTP_AUDIO_READ_TIMEOUT_SECONDS = 8
HTTP_AUDIO_MAX_CONSECUTIVE_TIMEOUTS = 8
HTTP_AUDIO_STREAM_BUFFER_BYTES = 1024
HTTP_STT_TIMEOUT_SECONDS = 120
HTTP_STT_RESPONSE_MAX_BYTES = 4096
DEBUG_MEMORY = False

PIN_AUDIO = 25
MAX_DAC_RATE = 8000
VOLUMEN_PORCENTAJE = 4

MIC_I2S_ID = 0
MIC_SCK = 14
MIC_WS = 27
MIC_SD = 32
MIC_SAMPLE_RATE = 16000
MIC_RECORD_SECONDS = 3
MIC_RAW_BUFFER_BYTES = 1024
MIC_I2S_BUFFER_BYTES = 20000

ENABLE_AUDIO_TEST = False
AUDIO_TEST_WAV_PATH = "/tts_prueba.wav"

MQTT_BROKER = _ACTIVE_PROFILE["MQTT_BROKER"]
MQTT_PORT = _ACTIVE_PROFILE["MQTT_PORT"]
MQTT_USER = _ACTIVE_PROFILE["MQTT_USER"]
MQTT_PASSWORD = _ACTIVE_PROFILE["MQTT_PASSWORD"]
MQTT_KEEPALIVE = _ACTIVE_PROFILE["MQTT_KEEPALIVE"]
MQTT_USE_TLS = _ACTIVE_PROFILE["MQTT_USE_TLS"]
MQTT_RECONNECT_DELAY = 5
MQTT_TOPIC_PREFIX = "device"
MQTT_TOPIC_SUFFIX = "audio"
