"""Example configuration for the ESP32 MicroPython application."""

WIFI_SSID = "YOUR_WIFI_SSID"
WIFI_PASSWORD = "YOUR_WIFI_PASSWORD"
WIFI_TIMEOUT_SECONDS = 15

BACKEND_HOST = "your-backend-host-or-ip"
BACKEND_PORT = 8000
REMINDERS_ENDPOINT = "/api/voice/reminders"
AUDIO_ENDPOINT_PREFIX = "/assistant/audio/"
STT_ENDPOINT = "/assistant/stt/"
TEMP_AUDIO_DOWNLOAD_PATH = "/assistant_audio.wav"
HTTP_CONNECT_TIMEOUT_SECONDS = 15
HTTP_SEND_TIMEOUT_SECONDS = 30
HTTP_AUDIO_READ_TIMEOUT_SECONDS = 8
HTTP_AUDIO_MAX_CONSECUTIVE_TIMEOUTS = 8
HTTP_STT_TIMEOUT_SECONDS = 120
HTTP_STT_RESPONSE_MAX_BYTES = 4096

PIN_AUDIO = 25
MAX_DAC_RATE = 8000
VOLUMEN_PORCENTAJE = 4

MIC_I2S_ID = 0
MIC_SCK = 14
MIC_WS = 27
MIC_SD = 32
MIC_SAMPLE_RATE = 16000
MIC_RECORD_SECONDS = 3
MIC_RAW_BUFFER_BYTES = 1024
MIC_I2S_BUFFER_BYTES = 20000

ENABLE_AUDIO_TEST = False
AUDIO_TEST_WAV_PATH = "/tts_prueba.wav"

MQTT_BROKER = "your-mqtt-host-or-ip"
MQTT_PORT = 1883
MQTT_USER = None
MQTT_PASSWORD = None
MQTT_KEEPALIVE = 60
MQTT_RECONNECT_DELAY = 5
MQTT_TOPIC_PREFIX = "device"
MQTT_TOPIC_SUFFIX = "audio"
