"""Shared constants for the voice assistant module."""

DEFAULT_AUDIO_SAMPLE_RATE = 16000
VOICE_AUDIO_DEBUG_DEFAULT = True
VOICE_RESPONSE_UNKNOWN_RESULT = "unknown"
VOICE_RESPONSE_SEMANTIC_MODEL_NAME = "paraphrase-multilingual-MiniLM-L12-v2"
VOICE_RESPONSE_SEMANTIC_THRESHOLD = 0.75
VOICE_RESPONSE_SEMANTIC_MIN_SCORE_MARGIN = 0.05
VOICE_TTS_VOICE = "es-CO-GonzaloNeural"
VOICE_TTS_OUTPUT_SAMPLE_RATE = 8000
VOICE_TTS_OUTPUT_CHANNELS = 1
VOICE_TTS_OUTPUT_SAMPLE_WIDTH_BYTES = 2
VOICE_TTS_OUTPUT_CODEC = "pcm_s16le"
VOICE_TTS_FILENAME_PREFIX = "tts_assignment"
