# Generated by Django 5.2.12 on 2026-05-04 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_elderly_caregiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elderly',
            name='caregiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elderlies', to='users.caregiver'),
        ),
    ]
