# Generated by Django 5.2.12 on 2026-05-04 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_caregiver_relationship_to_elderly_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elderly',
            name='relationship_to_caregiver',
            field=models.CharField(max_length=100),
        ),
    ]
