# Generated by Django 5.2.12 on 2026-06-06

from django.db import migrations, models


def copy_elderly_user_data(apps, schema_editor):
    Elderly = apps.get_model("users", "Elderly")

    for elderly in Elderly.objects.select_related("user").all():
        user = elderly.user
        elderly.first_name = user.first_name or ""
        elderly.last_name = user.last_name or ""
        elderly.age = None
        elderly.save(update_fields=["first_name", "last_name", "age"])


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_elderly_relationship_to_caregiver"),
    ]

    operations = [
        migrations.AddField(
            model_name="elderly",
            name="age",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="elderly",
            name="first_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="elderly",
            name="last_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.RunPython(copy_elderly_user_data, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="elderly",
            name="user",
        ),
        migrations.AlterField(
            model_name="elderly",
            name="first_name",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="elderly",
            name="last_name",
            field=models.CharField(max_length=150),
        ),
    ]
