# Generated by Django 5.2.12 on 2026-06-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='additional_instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
