# Generated by Django 5.2.12 on 2026-06-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0002_assignment_additional_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='frequency',
            field=models.CharField(choices=[('once', 'Once'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20),
        ),
    ]
