# Generated by Django 5.2.12 on 2026-06-06

import django.db.models.deletion
from django.db import migrations, models


def clear_routine_data(apps, schema_editor):
    Assignment = apps.get_model("routines", "Assignment")
    Program = apps.get_model("routines", "Program")

    Assignment.objects.all().delete()
    Program.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_refactor_elderly_remove_user_add_fields"),
        ("routines", "0003_alter_program_frequency"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="elderly",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="programs",
                to="users.elderly",
            ),
        ),
        migrations.RunPython(clear_routine_data, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="program",
            name="elderly",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="programs",
                to="users.elderly",
            ),
        ),
    ]
