# Generated by Django 5.2.12 on 2026-05-06 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_category_color_category_icon'),
        ('users', '0005_alter_elderly_relationship_to_caregiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='caregiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='users.caregiver'),
        ),
    ]
