# Generated by Django 5.2.12 on 2026-05-06 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_category_caregiver'),
        ('users', '0005_alter_elderly_relationship_to_caregiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='caregiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='users.caregiver'),
        ),
    ]
