# Generated by Django 5.2.12 on 2026-05-31 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_alter_category_caregiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='caregiver',
        ),
    ]
